version: '2'
services:
    iotcloudster-app:
        image: yannickmayeur/iotcloudster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://iotcloudster-mysql:3306/iotcloudster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=iotcloudster-elasticsearch:9300
        ports:
            - 8080:8080
    iotcloudster-mysql:
        image: mysql:5.7.20
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=iotcloudster
        command: >-
            mysqld --lower_case_table_names=1 --skip-ssl
            --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    iotcloudster-elasticsearch:
        image: elasticsearch:5.6.5
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
    
