version: '2'
services:
    iotcloudster-app:
        image: iotcloudster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://iotcloudster-mysql:3306/iotcloudster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=iotcloudster-elasticsearch:9300
        ports:
            - 8080:8080
    iotcloudster-mysql:
        extends:
            file: mysql.yml
            service: iotcloudster-mysql
    iotcloudster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: iotcloudster-elasticsearch
